language: cpp
sudo: false
compiler:
  - clang
  - gcc
branches:
  only:
    - master
before_install:
  - cat /etc/issue.net
script:
  - mkdir ./Build
  - cd ./Build
  - cmake ../
  - make
notifications:
  email: false
